#!/bin/bash
# Sync canonical source files into hf_space/ and push to the HF Space repo.
#
# Canonical sources (edit these):
#   scripts/explorer_app.py        — Bokeh entry point
#   scripts/explorer/              — extracted helper package (state, rendering,
#                                    persistence, html_views, images, activations,
#                                    runtime, registry, loaders)
#   scripts/bootstrap_demo.py      — registry-driven downloader + launcher
#   configs/models.yaml            — model registry (single source of truth)
#   src/clip_utils.py              — CLIP loader used by the explorer
#
# Usage:
#   scripts/sync_hf_space.sh [--no-push]

set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HF_DIR="$REPO_ROOT/hf_space"

NO_PUSH=0
for arg in "$@"; do
    [[ "$arg" == "--no-push" ]] && NO_PUSH=1
done

echo "Syncing canonical files into $HF_DIR ..."

# explorer_app.py — prepend a DO-NOT-EDIT banner, then the canonical content
{
cat <<'BANNER'
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# DO NOT EDIT THIS FILE DIRECTLY.
#
# This file is auto-synced from the canonical source:
#   scripts/explorer_app.py   (in the main project repo)
#
# To make changes:
#   1. Edit  scripts/explorer_app.py  (or scripts/explorer/*.py)
#   2. Run   scripts/sync_hf_space.sh
#
# That script copies the canonical files into this hf_space/ directory,
# commits, and pushes to the HF Space repo.
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

BANNER
cat "$REPO_ROOT/scripts/explorer_app.py"
} > "$HF_DIR/scripts/explorer_app.py"
echo "  -> hf_space/scripts/explorer_app.py"

# explorer/ package — straight mirror with --delete so removed modules
# propagate. Skip __pycache__ so the Space repo doesn't churn on local
# byte-compile artifacts.
mkdir -p "$HF_DIR/scripts/explorer"
rsync -a --delete --exclude='__pycache__' \
    "$REPO_ROOT/scripts/explorer/" "$HF_DIR/scripts/explorer/"
echo "  -> hf_space/scripts/explorer/ ($(ls "$HF_DIR/scripts/explorer" | wc -l | tr -d ' ') files)"

# Drop a small banner inside the package so anyone poking around knows
# it's auto-synced (per-file banners across 7+ files would be more noise
# than signal).
cat > "$HF_DIR/scripts/explorer/_AUTOSYNCED.md" <<'EOF'
This directory is auto-synced from `scripts/explorer/` in the main project
repo via `scripts/sync_hf_space.sh`. Do not edit files here directly —
your changes will be overwritten on the next sync.
EOF

# clip_utils.py — straight copy (no HF-specific divergence)
cp "$REPO_ROOT/src/clip_utils.py" "$HF_DIR/src/clip_utils.py"
echo "  -> hf_space/src/clip_utils.py"

# backbone_runners.py + precompute_utils.py — used by the explorer's
# on-demand patch-activations inference path.
cp "$REPO_ROOT/src/backbone_runners.py" "$HF_DIR/src/backbone_runners.py"
cp "$REPO_ROOT/src/precompute_utils.py" "$HF_DIR/src/precompute_utils.py"
echo "  -> hf_space/src/backbone_runners.py"
echo "  -> hf_space/src/precompute_utils.py"

# bootstrap_demo.py — registry-driven downloader + launcher used by entrypoint.sh
cp "$REPO_ROOT/scripts/bootstrap_demo.py" "$HF_DIR/scripts/bootstrap_demo.py"
echo "  -> hf_space/scripts/bootstrap_demo.py"

# configs/models.yaml — model registry (single source of truth)
mkdir -p "$HF_DIR/configs"
cp "$REPO_ROOT/configs/models.yaml" "$HF_DIR/configs/models.yaml"
echo "  -> hf_space/configs/models.yaml"

if [[ $NO_PUSH -eq 1 ]]; then
    echo "Skipping git commit/push (--no-push)."
    exit 0
fi

cd "$HF_DIR"
git add scripts/explorer_app.py scripts/explorer scripts/bootstrap_demo.py \
        configs/models.yaml src/clip_utils.py src/backbone_runners.py \
        src/precompute_utils.py Dockerfile entrypoint.sh

if git diff --cached --quiet; then
    echo "No changes to commit."
    exit 0
fi

git commit -m "Sync explorer source from main repo"
git push
echo "Done — HF Space updated."
